# Generated by Django 3.2.5 on 2021-07-31 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelform',
            name='date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='modelform',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
