# Generated by Django 3.2.5 on 2021-07-31 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoform', '0002_auto_20210731_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelform',
            name='date',
            field=models.DateField(blank=True),
        ),
    ]
