# Generated by Django 3.2.5 on 2021-07-31 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoform', '0004_alter_modelform_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelform',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
