# Generated by Django 3.2.5 on 2021-08-05 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoform', '0005_alter_modelform_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelform',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
