version: "3"


services:
  mongodb:
    image: mongo:latest
    container_name: mongo
    restart: always 
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb_volume:/data/db

  web: 
    build: .
    command: bash -c "python3 ./manage.py makemigrations && python3 ./manage.py migrate && python3 ./manage.py runserver 0.0.0.0:8000"
    restart: always 
    volumes: 
      - static_value:/code/static/
    ports:
      - 8000:8000
    depends_on: 
      - mongodb


volumes: 
  mongodb_volume:
  static_value: 
