# Generated by Django 3.2.5 on 2021-07-31 08:56

import django.utils.timezone
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='EmailOrder', max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='RU')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('text', models.TextField(blank=True)),
            ],
        ),
    ]
